import { StyleSheet } from 'react-native';
import Colors from '@colors';
import font from '@components/config/font';

export default StyleSheet.create({
  ActivityItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: Colors.Unfocused_Blue,
    borderRadius: 20,
    padding: 10,
    position: 'relative',
    minHeight: 100,
    maxHeight: 100,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    // backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  StatusIconContainer: {
    position: 'absolute',
    left: -10,
    top: -10,
    backgroundColor: Colors.primary,
    borderRadius: 100,
    width: 25,
    height: 25,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  StatusIcon: {},
  notificationCircle: {
    backgroundColor: Colors.hot_red,
    position: 'absolute',
    left: -5,
    top: -5,
    borderRadius: 100,
    width: 10,
    height: 10,
  },
  notificationIconContainer: { position: 'relative' },
  headerContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 2,
  },
  footerContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
  },
  ReceiptText: {
    fontFamily: font.PublicSans_700Bold,
    color: Colors.fontColor,
    fontSize: 16,
  },
  StatusContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  StatusTitleText: {
    fontFamily: font.PublicSans_700Bold,
    color: Colors.fontColor,
    fontSize: 16,
  },
  StatusText: {
    fontFamily: font.PublicSans_600SemiBold,
    color: Colors.fontColor,
    fontSize: 14,
  },
  numReqText: {
    fontFamily: font.PublicSans_700Bold,
    color: Colors.primary,
    fontSize: 14,
  },
  truckLogo: {},
  priceContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  TotalText: {
    fontFamily: font.PublicSans_700Bold,
    color: Colors.fontColor,
    fontSize: 14,
  },
  price: {
    color: Colors.goodGreen,
    fontFamily: font.PublicSans_800ExtraBold,
    fontSize: 14,
  },
  tag: {
    color: Colors.primary,
    fontFamily: font.PublicSans_800ExtraBold,
    fontSize: 14,
  },
  menuButton: {},
  timerContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 2,
    position: 'absolute',
    right: 10,
    top: 10,
  },
  timerText: {
    color: Colors.fontColor,
    fontFamily: font.PublicSans_600SemiBold,
    fontSize: 13,
  },
  time: {
    color: Colors.primary,
    fontFamily: font.PublicSans_900Black,
    fontSize: 14,
  },
  popMenu: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderColor: Colors.Unfocused_Blue,
    borderRadius: 20,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    padding: 5,
    position: 'absolute',
    right: -10,
    bottom: -10,
  },
  hereButtonContainer: {},
  hereButton: {
    backgroundColor: Colors.primary,
  },
  hereButtonText: {
    color: Colors.white,
    fontFamily: font.PublicSans_600SemiBold,
    fontSize: 12,
  },
});
